### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by Bakual**
Enjoy!

### CODE REVIEW

**Comment by infograf768** [comment]
I do not understand this. It is not compliant to https://github.com/joomla/joomla-cms/pull/19353

The name of the files contain the en-GB.suffix

**Comment by Bakual** [comment]
Yes, that is exactly the problem I try to solve with the other PR. The filenames generated by Crowdin are wrong and can't be made to fit.

If it gets accepted, we can rename the weblinks files and then this PR here gets automatically updated with the new filenames and the Crowdin/GitHub integration would work nicely.

**Comment by infograf768** [comment]
Can't we just get Crowdin to modify its API to let it be customised to fit our needs?

**Comment by Bakual** [comment]
Actually, I think Crowdin allows to do it as of today. But it means you have to configure each file individually and set an export filename. But that's quite a bit of work and needs to be done everytime a new file gets added. It's much simpler if you can just point it to the folder.
The same is already true for the core language packs. I had to configure every single file so the exported filename is correct.

The way Crowdin builds the filenames is that they split the path by "/" and let you build it with blocks again for the exported file. Eg `/src/administrator/components/com_weblinks/language/%locale%/%original_file_name%`
It has quite a few building blocks (%original_file_name%, %original_path%, %file_extension%, %file_name%, %language%, %two_letters_code%, %three_letters_code%, %locale%, %locale_with_underscore%, %android_code%, %osx_code%, %osx_locale%).

But we can't replace **parts** of the filename. Crowdin would have to split the filename by the dots and then let us build it again. Honestly I doubt they will do that.
I can ask them, but given how simple it actually is on our end to support non-prefixed filenames, I would rather change it on our end.

**Comment by infograf768** [comment]
> But it means you have to configure each file individually and set an export filename. But that's quite a bit of work and needs to be done everytime a new file gets added.

Understand. Grr...

**Pull request closed without merging**
